//! # RSC — Rust Smart Components
//!
//! React-like, compile-time components for Rust. A component is a struct (its
//! fields are its props) paired with a `.rsc` template. The [`component!`] macro
//! compiles the template into a [`Component::render_into`] method, so rendering
//! is plain Rust with no runtime template parsing.
//!
//! ```ignore
//! use rsc::Component;
//!
//! // greeting.rs  — paired with greeting.html.rsc containing: Hello <%= self.name %>!
//! #[derive(Component)]
//! pub struct Greeting {
//!     pub name: String,
//! }
//!
//! let out = Greeting { name: "Ada".into() }.render();
//! assert_eq!(out, "Hello Ada!");
//! ```
//!
//! ## The two traits
//!
//! - [`Renderer`] is the extensibility seam: it owns the output buffer and the
//!   escaping policy. Implement it to change escaping, target a different sink,
//!   or stream. Components render into `&mut dyn Renderer`, so a component
//!   compiled once works with any renderer.
//! - [`Component`] is implemented by the macro. [`Component::render`] renders to
//!   a `String` using the default renderer chosen by the template's host
//!   language.
//!
//! See [`renderers`] for the built-ins and [`StringRenderer`](renderers::StringRenderer)
//! for the easiest custom-renderer starting point.

use std::fmt::Display;

pub mod renderers;

pub use renderers::{CssRenderer, HtmlRenderer, JsRenderer, PlainRenderer};

/// Derive macro that generates a [`Component`] impl from a struct's paired
/// `.rsc` template. Shares its name with the trait (like `serde::Serialize`), so
/// `use rsc::Component;` brings both into scope.
pub use rsc_macros::Component;

/// A sink that accumulates rendered output and owns the escaping policy.
///
/// This trait is **object-safe on purpose**. The `component!` macro emits a
/// [`Component::render_into`] that writes into `&mut dyn Renderer`, so a single
/// compiled component can be driven by any renderer — a built-in
/// ([`HtmlRenderer`] and friends) or a third-party one with custom escaping, a
/// non-`String` backing store exposed through [`finish`](Renderer::finish), or
/// streaming behavior.
pub trait Renderer {
    /// Append text with no transformation.
    ///
    /// Literal template text and already-safe content (such as a child
    /// component's rendered output) go through here.
    fn write_raw(&mut self, s: &str);

    /// Append a value, applying this renderer's escaping policy.
    ///
    /// Backs the `<%= … %>` tag.
    fn write_escaped(&mut self, value: &dyn Display);

    /// Append a value with no escaping.
    ///
    /// Backs the `<%- … %>` tag. The default formats through
    /// [`write_raw`](Renderer::write_raw); renderers backed by a buffer should
    /// override it to write in place.
    fn write_display_raw(&mut self, value: &dyn Display) {
        self.write_raw(&value.to_string());
    }

    /// Consume the renderer and produce the finished output.
    fn finish(self: Box<Self>) -> String;
}

/// A renderable component.
///
/// Generated by the [`component!`] macro from a struct plus its `.rsc` template.
/// The trait is object-safe, so `&dyn Component` and `Vec<Box<dyn Component>>`
/// work for dynamic composition.
pub trait Component {
    /// Write this component's output into `r`. Generated from the template.
    fn render_into(&self, r: &mut dyn Renderer);

    /// The renderer chosen by the template's host language, used by
    /// [`render`](Component::render).
    fn default_renderer(&self) -> Box<dyn Renderer>;

    /// Render to a `String` using the [default renderer](Component::default_renderer).
    fn render(&self) -> String {
        let mut r = self.default_renderer();
        self.render_into(r.as_mut());
        r.finish()
    }
}

/// Common imports for authoring and using components.
///
/// `Component` here is both the trait and its derive macro.
pub mod prelude {
    pub use crate::renderers::{CssRenderer, HtmlRenderer, JsRenderer, PlainRenderer, StringRenderer};
    pub use crate::{Component, Renderer};
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::renderers::{HtmlRenderer, StringRenderer, escape_html};

    // A hand-written component, standing in for macro output until M3 exists.
    struct Greeting {
        name: String,
    }

    impl Component for Greeting {
        fn render_into(&self, r: &mut dyn Renderer) {
            r.write_raw("Hello ");
            r.write_escaped(&self.name);
            r.write_raw("!");
        }

        fn default_renderer(&self) -> Box<dyn Renderer> {
            Box::new(HtmlRenderer::new())
        }
    }

    #[test]
    fn render_uses_default_renderer_and_escapes() {
        let g = Greeting {
            name: "<Ada>".into(),
        };
        assert_eq!(g.render(), "Hello &lt;Ada&gt;!");
    }

    #[test]
    fn render_into_accepts_any_renderer() {
        // Drive the same component through a bespoke renderer: prove the seam.
        let g = Greeting { name: "Bob".into() };
        let mut custom: Box<dyn Renderer> = Box::new(StringRenderer::with_escape(escape_html));
        g.render_into(custom.as_mut());
        assert_eq!(custom.finish(), "Hello Bob!");
    }

    #[test]
    fn components_are_object_safe() {
        let items: Vec<Box<dyn Component>> = vec![
            Box::new(Greeting { name: "a".into() }),
            Box::new(Greeting { name: "b".into() }),
        ];
        let out: String = items.iter().map(|c| c.render()).collect();
        assert_eq!(out, "Hello a!Hello b!");
    }
}
